-- MySQL Script generated by MySQL Workbench
-- Sat Nov 18 18:20:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `id_cliente` INT NOT NULL,
  `cuit` VARCHAR(25) NOT NULL,
  `razonSocial` VARCHAR(255) NOT NULL,
  `mail` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `CUIT_UNIQUE` (`cuit` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes_servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes_servicios` (
  `id_cliente` INT NOT NULL,
  `id_servicios` INT NOT NULL,
  INDEX `fk_clientes_servicios_servicios1_idx` (`id_servicios` ASC) VISIBLE,
  INDEX `fk_clientes_servicios_clientes1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_servicios_servicios1`
    FOREIGN KEY (`id_servicios`)
    REFERENCES `mydb`.`servicios` (`id_servicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_servicios_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`especialidades` (
  `id_especialidades` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_especialidades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`incidentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`incidentes` (
  `id_incidentes` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_servicios` INT NOT NULL,
  `id_especialidades` INT NOT NULL,
  `id_tecnicos` INT NOT NULL,
  `tiempo_estimado_resolucion` VARCHAR(45) NOT NULL,
  `fecha_posible_resolucion` DATE NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `consideraciones` TEXT(255) NULL,
  PRIMARY KEY (`id_incidentes`),
  INDEX `fk_incidente_cliente1_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_incidente_tecnico1_idx` (`id_tecnicos` ASC) VISIBLE,
  INDEX `fk_incidentes_servicios1_idx` (`id_servicios` ASC) VISIBLE,
  INDEX `fk_incidentes_especialidades1_idx` (`id_especialidades` ASC) VISIBLE,
  CONSTRAINT `fk_incidente_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incidente_tecnico1`
    FOREIGN KEY (`id_tecnicos`)
    REFERENCES `mydb`.`tecnicos` (`id_tecnicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incidentes_servicios1`
    FOREIGN KEY (`id_servicios`)
    REFERENCES `mydb`.`servicios` (`id_servicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incidentes_especialidades1`
    FOREIGN KEY (`id_especialidades`)
    REFERENCES `mydb`.`especialidades` (`id_especialidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`operador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`operador` (
  `id_operador` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_operador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`operador_incidentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`operador_incidentes` (
  `id_operador` INT NOT NULL,
  `id_incidentes` INT NOT NULL,
  INDEX `fk_operador_incidentes_incidentes1_idx` (`id_incidentes` ASC) VISIBLE,
  INDEX `fk_operador_incidentes_operador1_idx` (`id_operador` ASC) VISIBLE,
  CONSTRAINT `fk_operador_incidentes_incidentes1`
    FOREIGN KEY (`id_incidentes`)
    REFERENCES `mydb`.`incidentes` (`id_incidentes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_operador_incidentes_operador1`
    FOREIGN KEY (`id_operador`)
    REFERENCES `mydb`.`operador` (`id_operador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicios` (
  `id_servicios` INT NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_servicios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tecnicos` (
  `id_tecnicos` INT NOT NULL,
  `dni` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `apellido` VARCHAR(255) NOT NULL,
  `celular` VARCHAR(255) NOT NULL,
  `medio_de_notificacion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_tecnicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tecnicos_especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tecnicos_especialidades` (
  `id_tecnicos` INT NOT NULL,
  `id_especialidades` INT NOT NULL,
  INDEX `fk_tecnicos_especialidades_especialidades1_idx` (`id_especialidades` ASC) VISIBLE,
  INDEX `fk_tecnicos_especialidades_tecnicos1_idx` (`id_tecnicos` ASC) VISIBLE,
  CONSTRAINT `fk_tecnicos_especialidades_especialidades1`
    FOREIGN KEY (`id_especialidades`)
    REFERENCES `mydb`.`especialidades` (`id_especialidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tecnicos_especialidades_tecnicos1`
    FOREIGN KEY (`id_tecnicos`)
    REFERENCES `mydb`.`tecnicos` (`id_tecnicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
